server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Ocultar la versión de Nginx
    server_tokens off;

    # Previene Clickjacking (solo permite embeber iframes del mismo origen)
    add_header X-Frame-Options "SAMEORIGIN" always;
    # Previene ataques de inyección forzando al navegador a respetar los tipos MIME
    add_header X-Content-Type-Options "nosniff" always;
    # Controla la información de referer enviada a otros sitios
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    # Content Security Policy (CSP) restrictiva (Ajustar URLs según los servicios externos que use Vite/React)
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://storage.googleapis.com; connect-src 'self' http://localhost:8000 https://*.livemenu.app;" always;
    # Fuerza HTTP Strict Transport Security (HSTS) para conexiones SSL
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Soporte para React/Vite SPA (Redirige los 404 a index.html)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bloquear el acceso a archivos ocultos
    location ~ /\. {
        deny all;
    }

    # Caché estática para mejorar el rendimiento
    location ~* \.(?:css|js|jpg|svg|webp|png)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}