"""add_slug_and_fix_restaurant_relations

Revision ID: 5147191857b1
Revises: 98b9b6e87adb
Create Date: 2026-02-24 23:36:04.361432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5147191857b1'
down_revision = '98b9b6e87adb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('restaurants', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_restaurants_slug'), 'restaurants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_slug'), table_name='restaurants')
    op.drop_column('restaurants', 'description')
    op.drop_column('restaurants', 'slug')
    # ### end Alembic commands ###

