"""add owner_id

Revision ID: 98b9b6e87adb
Revises: a18da294ac8c
Create Date: 2026-02-07 17:03:36.006651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b9b6e87adb'
down_revision = 'a18da294ac8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'restaurants', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'owner_id')
    # ### end Alembic commands ###

