"""create restaurants table

Revision ID: a18da294ac8c
Revises: 8b49c7ee2ffa
Create Date: 2026-02-07 16:43:58.656978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18da294ac8c'
down_revision = '8b49c7ee2ffa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address', sa.String(), nullable=True))
    op.drop_index('ix_restaurants_slug', table_name='restaurants')
    op.drop_constraint('restaurants_owner_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'slug')
    op.drop_column('restaurants', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('restaurants_owner_id_fkey', 'restaurants', 'users', ['owner_id'], ['id'])
    op.create_index('ix_restaurants_slug', 'restaurants', ['slug'], unique=False)
    op.drop_column('restaurants', 'address')
    # ### end Alembic commands ###

