"""create_categories_and_dishes_tables

Revision ID: fcaef81be286
Revises: 5147191857b1
Create Date: 2026-02-24 23:42:52.166116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaef81be286'
down_revision = '5147191857b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

